return {
	armjanus = {
		buildpic = "ARMJANUS.DDS",
		buildtime = 3550,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "25 12 33",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 2600,
		explodeas = "mediumExplosionGeneric",
		footprintx = 2,
		footprintz = 2,
		health = 1030,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		maxacc = 0.02111,
		maxdec = 0.04222,
		maxslope = 10,
		maxwaterdepth = 12,
		metalcost = 240,
		movementclass = "TANK3",
		movestate = 0,
		nochasecategory = "VTOL",
		objectname = "Units/ARMJANUS.s3o",
		script = "Units/ARMJANUS.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 325,
		speed = 54,
		trackoffset = 3,
		trackstrength = 6,
		tracktype = "armstump_tracks",
		trackwidth = 29,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.29228,
		turnrate = 271,
		usepiececollisionvolumes = 1,
		customparams = {
			model_author = "Beherith",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmVehicles",
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-1.45095062256 -4.56400614014 0.266441345215",
				collisionvolumescales = "28.8743438721 18.1917877197 33.2305145264",
				collisionvolumetype = "Box",
				damage = 628,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 147,
				object = "Units/armjanus_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 364,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 59,
				object = "Units/arm2X2C.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tnkt1rockok",
			},
			select = {
				[1] = "tnkt1rocksel",
			},
		},
		weapondefs = {
			janus_rocket = {
				areaofeffect = 240,
				avoidfeature = false,
				craterareaofeffect = 240,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.85,
				energypershot = 0,
				explosiongenerator = "custom:genericshellexplosion-large-aoe",
				gravityaffected = "true",
				impulsefactor = 0.9,
				name = "Heavy AoE g2g plasma cannon",
				noselfdamage = true,
				range = 700,
				reloadtime = 6.73333,
				soundhit = "bertha6",
				soundhitwet = "splslrg",
				soundstart = "BERTHA1",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 307.40851,
				damage = {
					default = 800,
					subs = 100,
					vtol = 111,
				},
		},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "JANUS_ROCKET",
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				def = "JANUS_ROCKET",
				onlytargetcategory = "SURFACE",
				slaveto = 1,
			},
		},
	},
}
